### ISSUE TITLE
Implement and Configure MKDocs

### ISSUE THREAD

**Issue by dangkv** [dangkv/iracing_garage#13]
I want Mkdocs to host iracing_garage documentations in `./docs`. 
Configure MkDocs so that it is hosting the methods file. 
No need to worry about the theme yet.

## Resources:
- Inspiration: https://esterni.github.io/pyracing/
- https://www.mkdocs.org/getting-started/
- https://www.youtube.com/watch?v=Q-YA_dA8C20

**Comment by hmkamel** [comment]
Since I'm not the author of the repo - I cant access the repo settings.

Here is the link to the [pull request](https://github.com/dangkv/iracing_garage/pull/17)

You will need to do the following: 

### Setting up Github Pages

1. `GitHub Pages Settings:` Go to your GitHub repository's settings and navigate to the "Pages" section.
2. `Source:` Under "Source," select the branch.
3. `Save dat shit`

### Verification

1. `GitHub Page Process:` Once GitHub Pages processes your files, your documentation should be accessible at a URL like `https://<username>.github.io/<repository-name>`. 
2. Replace <username> and <repository-name> with your actual details.
